export const projects = [
    {
      id: 1,
      title: "food analyzer",
      description:
        "//... web analysis food using ai for checking nutrition;",
      tech: ["Next.js", "Tailwind.css", "OpenRouter AI", "Cloudinary"],
      image: "/ssproject1.svg",
      github: "https://github.com/edwinsatya/food-analyzer",
      live: "https://food-analyzer.touchsimpledev.site",
    },
    {
      id: 2,  
      title: "DeskLab",
      description:
        "//... web rental for setup your workspace. Confused? you can ask Desklab bot in the live chat for assistance;",
      tech: ["Next.js", "Tailwind.css", "OpenRouter AI", "zustand"],
      image: "/ssproject2.svg",
      github: "https://github.com/edwinsatya/DeskLab",
      live: "https://desklab.touchsimpledev.site/",
    },
    {
      id: 3,
      title: "pokedex app",
      description: "//... Fun web xD, you can catch them all. Pokemon lovers must visit this app;",
      tech: ["Next.js", "Tailwind.css", "Graphql"],
      image: "/ssproject3.svg",
      github: "https://github.com/edwinsatya/pokedex",
      live: "https://pokedex.touchsimpledev.site",
    },
    {
      id: 4,
      title: "Tola Web",
      description:
        "//... Landing page for Tola Web, a web development service;",
      tech: ["Next.js", "Tailwind.css"],
      image: "/ssproject4.svg",
      github: "",
      live: "https://www.tola.solutions/",
    },
    {
      id: 5,
      title: "MileApp Tasks Management",
      description: "//... Register, Login and then you can manage your tasks;",
      tech: ["Nuxt", "Tailwind", "Node.js", "Express", "Mockapi.io"],
      image: "/ssproject5.svg",
      github: "https://github.com/edwinsatya/mileapp-client",
      live: "https://mileapp-tasks.touchsimpledev.site",
    },
    {
      id: 6,
      title: "Happy Farm Dashboard",
      description: "//... Dashboard for Happy Farm project, providing insights and management tools for farm operations;",
      tech: ["Next.js", "Node.js", "PostgreSQL", "Tailwind.css", "Prisma"],
      image: "/ssproject6.svg",
      github: "",
      live: "",
    },
    {
      id: 7,
      title: "Magloft.com",
      description: "//... Landing page for Magloft's digital publishing platform, showcasing their services and features;",
      tech: ["Next.js", "Tailwind.css"],
      image: "/ssproject7.svg",
      github: "",
      live: "https://magloft.com/",
    },
    {
      id: 8,
      title: "mini-google",
      description:
        "//...mini google search engine with minimal design, you can save news and read later;",
      tech: ["react", "serper.dev", "context-api"],
      image: "/ssproject8.svg",
      github: "https://github.com/edwinsatya/mini-google",
      live: "https://mini-google.touchsimpledev.site/",
    },
    {
      id: 9,
      title: "bountie-hunter",
      description:
        "//...web3 bountie company, you can stacking your token and get more rewards;",
      tech: ["Next.js", "Tailwind.css", "metamask", "web3"],
      image: "/ssproject9.svg",
      github: "",
      live: "https://bountiehunter.io/",
    },
    {
      id: 10,
      title: "coming soon",
      description:
        "//...not yet upload;",
      tech: ["Web3", "Solidity", "React"],
      image: "",
      github: "",
      live: "",
    },
  ];